### ISSUE TITLE
database 정보 노출 문제 

### ISSUE THREAD

**Issue by cheese10yun** [dev-cheese/cheese#2]
```yml
datasource:
    url: 
    username: 
    password:
    driver-class-name: com.mysql.jdbc.Driver
```
* application.yml 설정에서 데이터 베이스 중요 정보가 노출됨
* 해당 파일을 이그노어 시키기에는 다른 설정들 또한 물려있음
* 해결을 어떻게 할것인지 생각 해볼것
